"""init

Revision ID: d744e85ea671
Revises: f20ba2d2760d
Create Date: 2024-01-29 19:50:09.459956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd744e85ea671'
down_revision: Union[str, None] = 'f20ba2d2760d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trables',
                    sa.Column('ticket_id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.Text, nullable=False),
                    sa.Column('op', sa.Text, nullable=False),
                    sa.Column('contacts', sa.Text, nullable=False),
                    sa.Column('status', sa.Boolean, nullable=False,default=False),
                    sa.Column('user_id', sa.BIGINT, nullable=False),
                    sa.Column('media', sa.Text, nullable=True),
                    sa.PrimaryKeyConstraint('ticket_id'))



def downgrade() -> None:
    op.drop_table('trables')
